// <auto-generated />
using System;
using CarPaintingStudio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarPaintingStudio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CarPaintingStudio.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarBrand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CarYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CarPaintingStudio.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Специалист с над 15 години опит в автомобилното боядисване",
                            Email = "ivan.georgiev@carpaint.bg",
                            FullName = "Иван Георгиев",
                            HireDate = new DateTime(2010, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Phone = "0888123456",
                            Position = "Главен боядисвач",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Експерт по матови покрития и специални ефекти",
                            Email = "petar.dimitrov@carpaint.bg",
                            FullName = "Петър Димитров",
                            HireDate = new DateTime(2017, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Phone = "0888234567",
                            Position = "Боядисвач",
                            YearsOfExperience = 8
                        });
                });

            modelBuilder.Entity("CarPaintingStudio.Models.GalleryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarBrand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GalleryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AfterImageUrl = "/images/gallery/merc-after.jpg",
                            BeforeImageUrl = "/images/gallery/merc-before.jpg",
                            CarBrand = "Mercedes",
                            CarModel = "E-Class",
                            CompletedDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2026, 2, 12, 21, 27, 33, 835, DateTimeKind.Local).AddTicks(9170),
                            Description = "Пълно боядисване в перлено бяло със защитно покритие",
                            IsVisible = true,
                            Title = "Mercedes E-Class - Перлено бяло"
                        },
                        new
                        {
                            Id = 2,
                            AfterImageUrl = "/images/gallery/bmw-after.jpg",
                            BeforeImageUrl = "/images/gallery/bmw-before.jpg",
                            CarBrand = "BMW",
                            CarModel = "M3",
                            CompletedDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2026, 2, 12, 21, 27, 33, 835, DateTimeKind.Local).AddTicks(9175),
                            Description = "Специално матово покритие с керамична защита",
                            IsVisible = true,
                            Title = "BMW M3 - Матово черно"
                        });
                });

            modelBuilder.Entity("CarPaintingStudio.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 12, 21, 27, 33, 835, DateTimeKind.Local).AddTicks(9010),
                            Description = "Пълно боядисване на автомобила във всякакъв цвят по избор",
                            DurationDays = 7,
                            IsActive = true,
                            Name = "Пълно боядисване",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 12, 21, 27, 33, 835, DateTimeKind.Local).AddTicks(9014),
                            Description = "Боядисване на отделни елементи - врати, калници, капаци",
                            DurationDays = 3,
                            IsActive = true,
                            Name = "Частично боядисване",
                            Price = 800m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 2, 12, 21, 27, 33, 835, DateTimeKind.Local).AddTicks(9018),
                            Description = "Професионално полиране и нанасяне на защитно покритие",
                            DurationDays = 2,
                            IsActive = true,
                            Name = "Полиране и защита",
                            Price = 450m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 2, 12, 21, 27, 33, 835, DateTimeKind.Local).AddTicks(9029),
                            Description = "Специално матово покритие за уникален външен вид",
                            DurationDays = 8,
                            IsActive = true,
                            Name = "Матово боядисване",
                            Price = 3200m
                        });
                });

            modelBuilder.Entity("CarPaintingStudio.Models.Appointment", b =>
                {
                    b.HasOne("CarPaintingStudio.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CarPaintingStudio.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
